package com.tqs;
// This file was automatically generated by Selenium IDE
// Was then refactored to use JUnit 5
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.interactions.Actions;

public class B_ExportedTest {
    private WebDriver driver;

    @BeforeEach
    public void setUp() {
        driver = new ChromeDriver();
    }

    @AfterEach
    public void tearDown() {
        if (driver != null) {
            driver.quit();
        }
    }

    @Test
    public void tripbuy() {
        driver.get("https://blazedemo.com/");
        driver.manage().window().setSize(new Dimension(980, 1193));

        // Select "Mexico City" from the 'fromPort' dropdown
        WebElement fromPortDropdown = driver.findElement(By.name("fromPort"));
        fromPortDropdown.findElement(By.xpath("//option[. = 'Mexico City']")).click();

        // Select "London" from the 'toPort' dropdown
        WebElement toPortDropdown = driver.findElement(By.name("toPort"));
        toPortDropdown.findElement(By.xpath("//option[. = 'London']")).click();

        // Click the 'Find Flights' button
        driver.findElement(By.cssSelector(".btn-primary")).click();

        // Choose a flight and continue to the purchase page
        driver.findElement(By.cssSelector("tr:nth-child(5) .btn")).click();

        // Fill out the purchase form
        driver.findElement(By.id("inputName")).sendKeys("Johny");
        driver.findElement(By.id("address")).sendKeys("123 Rua qualquer");
        driver.findElement(By.id("city")).sendKeys("Cidade");
        driver.findElement(By.id("state")).sendKeys("Estado"); // Fill in state if required
        driver.findElement(By.id("zipCode")).sendKeys("02020");
        driver.findElement(By.id("creditCardNumber")).sendKeys("123456");
        driver.findElement(By.id("nameOnCard")).sendKeys("Johny Smith");
        driver.findElement(By.id("rememberMe")).click();

        // Click the 'Purchase Flight' button
        driver.findElement(By.cssSelector(".btn-primary")).click();

        // Assert that the title of the confirmation page is "BlazeDemo Confirmation"
        assertEquals("BlazeDemo Confirmation", driver.getTitle());
    }
}
